feeder: dataset.dataloader_video.BaseFeeder
phase: train
dataset: phoenix14
# dataset: phoenix14-si5
num_epoch: 80
work_dir: ./work_dir/temporal_2_vac_all/tp2vac_all
batch_size: 18
random_seed: 0
test_batch_size: 8
num_worker: 3
device: 0,1,2,3
log_interval: 50
eval_interval: 1
save_interval: 1
# python in default
evaluate_tool: python
loss_weights:
  ConvCTC: 1.0
  KeyCTC: 1.0
  SeqCTC: 1.0
  Dist: 10.0
  DistKey: 10.0
#  SeqFullFrameCTC: 1.0
#  SeqKeyCTC: 1.0

#load_weights: ./work_dir/with_keypoint_attn1_dev_25.70_test_25.71_epoch6_model.pt

optimizer_args:
  optimizer: Adam
  base_lr: 0.0001
  step: [ 10, 20, 30, 40, 50]
  learning_ratio: 1
  weight_decay: 0.0001
  start_epoch: 0
  nesterov: False

feeder_args:
  mode: 'train'
  datatype: 'video-keypoint'
#  datatype: 'video'
  num_gloss: -1
  drop_ratio: 1.0

#model: slr_network.SLRModel
model: slr_network_mf.SLRModelMF
decode_mode: beam
model_args:
  num_classes: 1296
  c2d_type: resnet18
  conv_type: 2
  use_bn: 1

# temporal attention config
use_temporal_attn: True
temporal_embedd_dim: 1024
temporal_n_heads: 4

#ignore_model_state_dict: ['temporal_model.rnn.weight_ih_l0', 'temporal_model.rnn.weight_ih_l0_reverse']