feeder: dataset.dataloader_csl.BaseFeeder
phase: train
dataset: csl
num_epoch: 80
work_dir: ./work_dir/csl_baseline/csl_baseline
batch_size: 2
random_seed: 0
test_batch_size: 4
num_worker: 6
device: 0
log_interval: 50
eval_interval: 1
save_interval: 1
# python in default
evaluate_tool: python
loss_weights:
#  ConvCTC: 1.0
#  KeyCTC: 1.0
  SeqCTC: 1.0
#  Dist: 10.0

#load_weights: ./work_dir/resnet18_slr_pretrained_distill25.pt
#load_checkpoints: ./work_dir/with_keypointdev_27.73_epoch29_model.pt

optimizer_args:
  optimizer: Adam
  base_lr: 0.0001
  step: [ 30, 40, 50, 60]
  learning_ratio: 1
  weight_decay: 0.0001
  start_epoch: 0
  nesterov: False

feeder_args:
  mode: 'train'
  datatype: 'video-keypoint'
#  datatype: 'video'
  num_gloss: -1
  drop_ratio: 1.0

#model: slr_network.SLRModel
model: slr_network_mf.SLRModelMF
decode_mode: beam
model_args:
  num_classes: 193
  c2d_type: resnet18
  conv_type: 2
  use_bn: 1

# spatial attention config
use_spatial_attn: False
spatial_embedd_dim: 512
spatial_n_heads: 2