feeder: dataset.dataloader_video.BaseFeeder
phase: train
dataset: phoenix14
# dataset: phoenix14-si5
num_epoch: 80
work_dir: ./work_dir/baseline_key_only/
batch_size: 8
random_seed: 0
test_batch_size: 8
num_worker: 10
device: 0
log_interval: 50
eval_interval: 1
save_interval: 1
# python in default
evaluate_tool: python
loss_weights:
#  ConvCTC: 1.0
#  KeyCTC: 1.0
  SeqCTC: 1.0
#  Dist: 10.0

load_weights: ./work_dir/baseline_key_only/_dev_40.36_test_39.48_epoch24_model.pt
#load_weights: ./work_dir/with_keypointdev_26.19_epoch70_model.pt
#load_weights: ./work_dir/with_keypoint_base/with_keypoint_dev_24.24_test_25.45_epoch48_model.pt
#load_weights: ./work_dir/with_keypoint_attn1_dev_28.65_test_28.58_epoch8_model.pt
#load_weights: ./work_dir/with_keypoint_attn1_dev_26.55_test_26.80_epoch30_model.pt
#load_checkpoints: ./work_dir/with_keypointdev_27.73_epoch29_model.pt
#load_checkpoints: ./work_dir/with_keypoint_dev_55.54_test_54.95_epoch2_model.pt

optimizer_args:
  optimizer: Adam
  base_lr: 0.00001
  step: [ 30, 40, 50, 60]
  learning_ratio: 1
  weight_decay: 0.0001
  start_epoch: 30
  nesterov: False

feeder_args:
  mode: 'train'
  datatype: 'video-keypoint'
#  datatype: 'video'
  num_gloss: -1
  drop_ratio: 1.0

model: slr_network_key.SLRModelMF
decode_mode: beam
model_args:
  num_classes: 1296
  c2d_type: resnet18
  conv_type: 2
  use_bn: 1

## spatial attention config
#use_spatial_attn: True
#spatial_embedd_dim: 512
#spatial_n_heads: 2